import telnetlib
import time
from pprint import pprint
import re
import os
host = '192.168.1.100'
def telnet(host):

    telnet = telnetlib.Telnet(host)
    telnet.read_until(b'Username')
    telnet.write(b'admin\n')
    telnet.read_until(b'Password')
    telnet.write(b'zxcvbn\n')
    telnet.read_until(b'>')
    telnet.write(b'_cmdline-mode on\n')
    telnet.read_until(b'?')
    telnet.write(b'Y\n')
    telnet.read_until(b':')
    telnet.write(b'512900\n')
    telnet.read_until(b'>')
    telnet.write(b'system-view\n')
    telnet.read_until(b']')
    telnet.write(b'dis cur\n')
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    time.sleep(1)
    all_result = telnet.read_very_eager().decode('utf-8')
    #print(all_result)
    telnet.close()

    return all_result

#replace("\r\n", "\n")

def telnetinterfaces(host):

    telnet = telnetlib.Telnet(host)
    telnet.read_until(b'Username')
    telnet.write(b'admin\n')
    telnet.read_until(b'Password')
    telnet.write(b'zxcvbn\n')
    telnet.read_until(b'>')
    telnet.write(b'_cmdline-mode on\n')
    telnet.read_until(b'?')
    telnet.write(b'Y\n')
    telnet.read_until(b':')
    telnet.write(b'512900\n')
    telnet.read_until(b'>')
    telnet.write(b'system-view\n')
    telnet.read_until(b']')
    telnet.write(b'dis interface\n')
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    time.sleep(1)
    all_result = telnet.read_very_eager().decode('utf-8')
    telnet.close()
    return all_result

def logging(host):

    telnet = telnetlib.Telnet(host)
    telnet.read_until(b'Username')
    telnet.write(b'admin\n')
    telnet.read_until(b'Password')
    telnet.write(b'zxcvbn\n')
    telnet.read_until(b'>')
    telnet.write(b'_cmdline-mode on\n')
    telnet.read_until(b'?')
    telnet.write(b'Y\n')
    telnet.read_until(b':')
    telnet.write(b'512900\n')
    telnet.read_until(b'>')
    telnet.write(b'system-view\n')
    telnet.read_until(b']')
    telnet.write(b'dis log rev\n')
    telnet.write(b" ")
    telnet.write(b" ")
    telnet.write(b" ")
    time.sleep(1)
    all_result = telnet.read_very_eager().decode('utf-8')
    #print(all_result)
    telnet.close()

    return all_result