# Generated by Django 4.0.4 on 2022-05-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='no connection', max_length=50, verbose_name='Статус')),
                ('label', models.CharField(max_length=50, verbose_name='Имя устройства')),
                ('model', models.CharField(max_length=50, verbose_name='Модель устройства')),
                ('ipaddr', models.GenericIPAddressField(verbose_name='IP Address')),
                ('mask', models.GenericIPAddressField(default='255.255.255.224', verbose_name='Маска')),
                ('categ', models.CharField(default='Switch', max_length=50, verbose_name='Категория')),
                ('binfile', models.CharField(blank=True, default='jg537a-cmw520-r1120.bin', max_length=50, verbose_name='Файл прошивки')),
                ('serial', models.CharField(blank=True, default='CN66G1H09L', max_length=50, verbose_name='Серийный номер')),
                ('reliz', models.CharField(blank=True, default='5.20.99 Release 1120', max_length=50, verbose_name='Версия релиза')),
                ('fullmodel', models.CharField(blank=True, default='HPE 3600-24-PoE+ (65W) Switch JG937A', max_length=50, verbose_name='Полная модель устройства')),
                ('contact', models.CharField(blank=True, default='37-99-53', max_length=50, verbose_name='Контакты')),
                ('ports', models.CharField(default='26', max_length=2, verbose_name='Количество портов')),
                ('notes', models.TextField(blank=True, default=' ', max_length=1150, verbose_name='Заметки')),
                ('location', models.CharField(blank=True, default='A18_R342', max_length=50, verbose_name='Локация')),
                ('cfg', models.TextField(blank=True, default='need connect', max_length=4150, verbose_name='Конфигурация')),
                ('interfaces', models.TextField(blank=True, default='need connect', max_length=4150, verbose_name='Интерфейсы')),
                ('logs', models.TextField(blank=True, default='need connect', max_length=8150, verbose_name='Логи')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
    ]
