# Generated by Django 4.0.4 on 2022-05-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0003_category_switch_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catname',
            field=models.CharField(default='Switch', max_length=50, verbose_name='Название'),
        ),
    ]
