# Generated by Django 4.0.4 on 2022-05-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0004_alter_category_catname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catname',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='category',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, to='switches.category', verbose_name='Категория'),
        ),
    ]
