# Generated by Django 4.0.4 on 2022-05-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0006_titul_alter_category_catname_switch_tit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='interfaces',
            field=models.TextField(blank=True, default='need connect', max_length=35150, verbose_name='Интерфейсы'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='logs',
            field=models.TextField(blank=True, default='need connect', max_length=20150, verbose_name='Логи'),
        ),
    ]
