# Generated by Django 4.0.4 on 2022-05-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0007_alter_switch_interfaces_alter_switch_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='mask',
            field=models.GenericIPAddressField(default='255.255.252.0', verbose_name='Маска'),
        ),
    ]
