# Generated by Django 4.0.4 on 2022-05-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0008_alter_switch_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='status',
            field=models.CharField(blank=True, default='no connection', max_length=50, verbose_name='Статус'),
        ),
    ]
