# Generated by Django 4.0.4 on 2022-05-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0009_alter_switch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='titul',
            name='zavod',
            field=models.CharField(blank='True', default='1 Зона', max_length=50, null='True', verbose_name='Завод'),
            preserve_default='True',
        ),
    ]
