# Generated by Django 4.0.4 on 2022-05-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0010_titul_zavod'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catcount',
            field=models.CharField(blank='True', max_length=50, null='True', verbose_name='Количество'),
            preserve_default='True',
        ),
    ]
