# Generated by Django 4.0.4 on 2022-06-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0012_alter_titul_zavod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titul',
            name='zavod',
            field=models.CharField(max_length=50, verbose_name='Завод'),
        ),
    ]
