# Generated by Django 4.0.4 on 2022-06-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0013_alter_titul_zavod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catcount',
        ),
        migrations.AddField(
            model_name='category',
            name='catlabel',
            field=models.CharField(max_length=50, null='True', verbose_name='Имя устройства'),
            preserve_default='True',
        ),
    ]
