# Generated by Django 4.0.4 on 2022-06-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0014_remove_category_catcount_category_catlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backname', models.CharField(max_length=50, verbose_name='Backupname')),
                ('bfile', models.CharField(max_length=50, verbose_name='bfile')),
                ('btime', models.CharField(max_length=50, verbose_name='Дата и время')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='catlabel',
            field=models.CharField(max_length=150, null='True', verbose_name='Имя устройства'),
        ),
        migrations.AddField(
            model_name='switch',
            name='backkey',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.PROTECT, to='switches.backup', verbose_name='Бекап'),
            preserve_default='True',
        ),
    ]
