# Generated by Django 4.0.4 on 2022-06-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0015_backup_alter_category_catlabel_switch_backkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='backname',
            field=models.CharField(max_length=50, verbose_name='Имя бекапа'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='bfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='backup',
            name='btime',
            field=models.DateTimeField(auto_now=True, max_length=50, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='category',
            name='catlabel',
            field=models.CharField(max_length=150, null='True', verbose_name='Описание'),
        ),
    ]
