# Generated by Django 4.0.4 on 2022-06-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('switches', '0016_alter_backup_backname_alter_backup_bfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='backkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='switches.backup', verbose_name='Бекап'),
        ),
    ]
